name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Basic checks - ensure code can build and run normally
  basic-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        npm ci
        pip install -r backend/scraper/requirements.txt
    
    - name: Code format check
      run: |
        npm run lint
        npx tsc --noEmit
    
    - name: Build check
      run: npm run build
      env:
        DATABASE_URL: postgresql://test:test@localhost:5432/test_db
    
    - name: Python syntax check
      run: |
        pip install flake8
        flake8 backend/scraper/ --max-line-length=88 --extend-ignore=E203,W503
    
    - name: Security check (non-blocking)
      run: |
        npm audit --audit-level high || echo "Found security issues, please check"
        pip install safety
        safety check -r backend/scraper/requirements.txt || echo "Found Python security issues, please check"
      continue-on-error: true
